import Head from 'next/head';
import NavBar from './NavBar';
import Image from 'next/image';


export default function Home() {
  return (
    <div className="md:w-[50%] w-[90%] mx-auto">
      <Head>
        <title>XRPL Token App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/db-logo.png" />
      </Head>
      <NavBar />
      {/* User Info */}
      <div className="flex items-center mt-10">
        <div className="">
          <Image
            src="/bg.jpg"
            alt="User Avatar"
            width={100}
            height={100}
            className="w-12 h-12 rounded-full cursor-pointer transform hover:scale-110 transition-transform ease-out duration-300 object-cover"
          />
        </div>
        <div className="ml-4">
          <p className="text-slate-500 text-xs">
            Welcome back
          </p>
          <p className="text-slate-800 text-xm font-semibold">
            James Babonda
          </p>
        </div>
        <div className="ml-auto">
          <i className="fas fa-bell p-3 text-slate-600 cursor-pointer transform hover:scale-110 transition-transform ease-out duration-300 border hover:border-slate-500 rounded-full"></i>
        </div>
      </div>

      {/* Wallet Info */}
      <div className="p-5 text-center rounded-lg text-xs bg-slate-100 my-6 space-y-2">
        <p>Total Balance</p>
        <h5 className="font-bold text-lg">
          ₦234,890.00
        </h5>
      </div>

      {/* Services */}
      <div className="text-slate-500 my-10">
        <p className="text-center text-sm mb-2 font-semibold">
          Quick Services
        </p>
        <div className="flex items-center justify-between w-[80%] mx-auto">
          <div className="flex flex-col items-center bg-slate-100 rounded-lg py-4 px-8 hover:scale-110">
            <i className="fa-solid fa-money-bill-trend-up text-2xl"></i>
            <p className="p-2 text-sm">Send</p>
          </div>
          <div className="flex flex-col items-center bg-slate-100 rounded-lg py-4 px-8 hover:scale-110">
            <i className="fa-solid fa-piggy-bank text-2xl "></i>
            <p className="p-2 text-sm">Invest</p>
          </div>
          <div className="flex flex-col items-center bg-slate-100 rounded-lg py-4 px-8 hover:scale-110">
            <i className="fa-solid fa-file-invoice text-2xl"></i>
            <p className="p-2 text-sm">History</p>
          </div>
        </div>
      </div>

      {/* Recent Transactions */}
      <div className="text-slate-700 my-10">
        <p className="text-center text-sm  font-semibold mb-2">
          Recent Transactions
        </p>
        <div className="flex flex-col space-y-3 text-sm">
          <div className="flex items-center justify-between bg-slate-100 py-3 px-8 rounded-lg">
            <div>
              <p className='text-slate-400'>Personal Acc</p>
              <h5 className="font-bold text-base">
                ₦31,140.00
              </h5>
            </div>
            <div>
              <p className='text-slate-400'>23/Oct/2023</p>
              <h5 className="font-medium text-sm">
                Shopping
              </h5>
            </div>
          </div>

          <div className="flex items-center justify-between bg-slate-100 py-3 px-8 rounded-lg">
            <div>
              <p className='text-slate-400'>Family Acc</p>
              <h5 className="font-bold text-base">
                ₦72,205.00
              </h5>
            </div>
            <div>
              <p className='text-slate-400'>24/Oct/2023</p>
              <h5 className="font-medium text-sm">
                Family
              </h5>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
