import Head from 'next/head';
import styles from '../styles/Home.module.css';
import NavBar from './NavBar';

export default function Home() {
  return (
      <div className='md:w-[50%] w-[90%] mx-auto'>
        <Head>
          <title>XRPL Token App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
<NavBar/>
<p className='p-2 text-center rounded-lg bg-slate-100'>Home Page</p>
      </div>
  );
}
